[2023-07-22T11:31:24.706+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion-pq.spark_cleansing_task manual__2023-07-22T11:27:14.666178+00:00 [queued]>
[2023-07-22T11:31:24.723+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion-pq.spark_cleansing_task manual__2023-07-22T11:27:14.666178+00:00 [queued]>
[2023-07-22T11:31:24.724+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 3
[2023-07-22T11:31:24.745+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): spark_cleansing_task> on 2023-07-22 11:27:14.666178+00:00
[2023-07-22T11:31:24.753+0000] {standard_task_runner.py:57} INFO - Started process 543 to run task
[2023-07-22T11:31:24.759+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion-pq', 'spark_cleansing_task', 'manual__2023-07-22T11:27:14.666178+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/data_ingest_pq.py', '--cfg-path', '/tmp/tmpgc3leq5m']
[2023-07-22T11:31:24.763+0000] {standard_task_runner.py:85} INFO - Job 132: Subtask spark_cleansing_task
[2023-07-22T11:31:24.789+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-07-22T11:31:24.854+0000] {task_command.py:410} INFO - Running <TaskInstance: data_ingestion-pq.spark_cleansing_task manual__2023-07-22T11:27:14.666178+00:00 [running]> on host 195f909145c6
[2023-07-22T11:31:24.975+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion-pq' AIRFLOW_CTX_TASK_ID='spark_cleansing_task' AIRFLOW_CTX_EXECUTION_DATE='2023-07-22T11:27:14.666178+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-22T11:27:14.666178+00:00'
[2023-07-22T11:31:24.977+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-22T11:31:24.979+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/spark && python3 spark-cleansing.py']
[2023-07-22T11:31:25.007+0000] {subprocess.py:86} INFO - Output:
[2023-07-22T11:31:27.268+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-07-22T11:31:37.851+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2023-07-22T11:31:37.852+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2023-07-22T11:31:38.263+0000] {subprocess.py:93} INFO - 23/07/22 11:31:38 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-07-22T11:31:52.744+0000] {subprocess.py:93} INFO - [Stage 0:>                                                          (0 + 0) / 1][Stage 0:>                                                          (0 + 1) / 1]                                                                                /home/***/.local/lib/python3.7/site-packages/pyspark/context.py:317: FutureWarning: Python 3.7 support is deprecated in Spark 3.4.
[2023-07-22T11:31:52.745+0000] {subprocess.py:93} INFO -   warnings.warn("Python 3.7 support is deprecated in Spark 3.4.", FutureWarning)
[2023-07-22T11:31:52.746+0000] {subprocess.py:93} INFO - ######################################
[2023-07-22T11:31:52.746+0000] {subprocess.py:93} INFO - READING CSV FILE
[2023-07-22T11:31:52.747+0000] {subprocess.py:93} INFO - ######################################
[2023-07-22T11:31:52.747+0000] {subprocess.py:93} INFO - ######################################
[2023-07-22T11:31:52.747+0000] {subprocess.py:93} INFO - FORMAT STANDARIZATION
[2023-07-22T11:31:52.748+0000] {subprocess.py:93} INFO - ######################################
[2023-07-22T11:31:52.761+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-07-22T11:31:52.762+0000] {subprocess.py:93} INFO -   File "spark-cleansing.py", line 50, in <module>
[2023-07-22T11:31:52.762+0000] {subprocess.py:93} INFO -     when(df.education.endswith('4y'), regexp_replace(df.education, 'basic.4y', 'basic')) \
[2023-07-22T11:31:52.763+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.7/site-packages/pyspark/sql/dataframe.py", line 2978, in __getattr__
[2023-07-22T11:31:52.763+0000] {subprocess.py:93} INFO -     "'%s' object has no attribute '%s'" % (self.__class__.__name__, name)
[2023-07-22T11:31:52.764+0000] {subprocess.py:93} INFO - AttributeError: 'DataFrame' object has no attribute 'education'
[2023-07-22T11:31:53.971+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-07-22T11:31:53.999+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-07-22T11:31:54.005+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion-pq, task_id=spark_cleansing_task, execution_date=20230722T112714, start_date=20230722T113124, end_date=20230722T113154
[2023-07-22T11:31:54.036+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 132 for task spark_cleansing_task (Bash command failed. The command returned a non-zero exit code 1.; 543)
[2023-07-22T11:31:54.070+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-22T11:31:54.113+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
